### Author: Akshay Ijantkar
### Team: Aqua Wizards
### Project: Surfers Bible

# Import Libraries:

In [11]:
import pandas as pd
import numpy as np
import random
import matplotlib as plt
from matplotlib import pyplot
import seaborn as sns; sns.set()
from scipy.stats import norm 
import matplotlib.pyplot as plt
# For Linear regression
from sklearn.linear_model import LinearRegression
# For split given dataset into train and test set.
from sklearn.model_selection import train_test_split
# To verify models using this metrics 
from sklearn.metrics import mean_squared_error, r2_score

import statsmodels.formula.api as smf
from sklearn.linear_model import LinearRegression
from sklearn import metrics
# v
from matplotlib import rcParams
rcParams['figure.figsize'] = 50,50
import pandas_profiling
pd.set_option('display.max_rows', 1500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
from pandas import ExcelWriter
from pandas import ExcelFile

from pygeocoder import Geocoder

import sys
from weather_au import api
from weather_au import summary
from weather import place, observations, uv_index
import time

import json
import requests
from datetime import datetime, timedelta
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_validate

import catboost as ctb
from catboost import CatBoostRegressor, FeaturesData, Pool
from scipy.stats import uniform as sp_randFloat
from scipy.stats import randint as sp_randInt
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics.pairwise import cosine_similarity
from  sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import manhattan_distances
from sklearn.metrics.pairwise import pairwise_distances
import re
import pprint

import sqlite3
from sqlite3 import Error

from configparser import ConfigParser
import psycopg2
import psycopg2
from psycopg2 import Error
# from config import config

%matplotlib inline

C:\Users\aksha\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Using TensorFlow backend.
C:\Users\aksha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\aksha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\aksha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\aksha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\aksha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\aksha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

# LOAD BEACH DF:

In [12]:
dataset_path = r"D:\Monash_University_Stuff\Final_Semester\IE\Surfers_Bible_Code_Commit\Datasets\\"
beach_df = pd.read_csv(dataset_path + "Beach_Names_Table.csv")
# raw_clean_shark_df = pd.read_excel(dataset_path + "shark_file_geolocation_checkpoint.xlsx")
print("beach_df.shape = ", beach_df.shape)
beach_df.tail(5)

beach_df.shape =  (217, 10)

    State                Municipality  Name Id            Place Name Place Name Status Feature Type Code Feature Type   Longitude   Latitude  Place Id
212   VIC  MORNINGTON PENINSULA SHIRE    30020         WOOLLEY BEACH        REGISTERED              BEAC        BEACH  145.217719 -38.346592     29854
213   VIC           CORANGAMITE SHIRE    30167           WRECK BEACH        REGISTERED              BEAC        BEACH  143.212391 -38.754585      8900
214   VIC       SOUTH GIPPSLAND SHIRE    30401         YANAKIE BEACH        REGISTERED              BEAC        BEACH  146.269408 -38.810766     30079
215   VIC                 MOIRA SHIRE    30796  ZINETTIS BEACH NO. 1        REGISTERED              BEAC        BEACH  145.940647 -35.967047     30353
216   VIC                 MOIRA SHIRE    30797  ZINETTIS BEACH NO. 2        REGISTERED              BEAC        BEACH  145.935630 -35.970012     30354

# Unique no. of beaches:

In [13]:
len(beach_df["Place Name"].unique().tolist())

200

# Drop duplicate rows from place name column:

In [14]:
beach_df.drop_duplicates(subset = ['Place Name'], 
                         keep = "first",
                         inplace = True)

beach_df.reset_index(drop = True, 
                    inplace = True)
beach_df.shape

(200, 10)

In [15]:
beach_df.head()

  State          Municipality  Name Id      Place Name Place Name Status Feature Type Code Feature Type   Longitude   Latitude  Place Id
0   VIC      SURF COAST SHIRE       74  ADDISCOT BEACH        REGISTERED              BEAC        BEACH  144.256782 -38.382328      9166
1   VIC           MOIRA SHIRE      443      APEX BEACH        REGISTERED              BEAC        BEACH  145.547011 -35.813031      9451
2   VIC      BASS COAST SHIRE      797      BACK BEACH        REGISTERED              BEAC        BEACH  145.369549 -38.526863      9663
3   VIC  GREATER GEELONG CITY     1174  BANCOORA BEACH        REGISTERED              BEAC        BEACH  144.407114 -38.291445      9923
4   VIC      BASS COAST SHIRE    31788     BARRY BEACH        HISTORICAL              BEAC        BEACH  145.203230 -38.517627     10558

In [16]:
beach_df.columns.tolist()

['State',
 'Municipality',
 'Name Id',
 'Place Name',
 'Place Name Status',
 'Feature Type Code',
 'Feature Type',
 'Longitude',
 'Latitude',
 'Place Id']

# Select require columns and rename columns:

In [17]:
beach_df = beach_df[['Place Name',
                     'Latitude',                        
                     'Longitude',                  
                     'State',
                     'Municipality',
                    ]]
beach_df.rename(columns = {"Place Name": "beach_name",
                           "Latitude": "beach_latitude",
                           "Longitude": "beach_longitude",
                           "State": "beach_state",
                           "Municipality": "beach_municipality"},
                inplace = True)

beach_df.head()

       beach_name  beach_latitude  beach_longitude beach_state    beach_municipality
0  ADDISCOT BEACH      -38.382328       144.256782         VIC      SURF COAST SHIRE
1      APEX BEACH      -35.813031       145.547011         VIC           MOIRA SHIRE
2      BACK BEACH      -38.526863       145.369549         VIC      BASS COAST SHIRE
3  BANCOORA BEACH      -38.291445       144.407114         VIC  GREATER GEELONG CITY
4     BARRY BEACH      -38.517627       145.203230         VIC      BASS COAST SHIRE

In [18]:
# beach_df.beach_name = beach_df.beach_name.apply(lambda x: x.capitalize())
# beach_df.head()

# Save in CSV:

In [19]:
beach_df.to_csv(dataset_path + "clean_beach_df.csv", 
                index = False)

In [20]:
beach_df.columns.tolist()

['beach_name',
 'beach_latitude',
 'beach_longitude',
 'beach_state',
 'beach_municipality']

In [72]:
cursor.close()
connection.close()

In [8]:
import psycopg2 as ps

# define credentials 
credentials = {'POSTGRES_ADDRESS' : 'test-surfers-bible-instance.cljoljhkgpfb.ap-southeast-2.rds.amazonaws.com', # change to your endpoint
               'POSTGRES_PORT' : 5432, # change to your port
               'POSTGRES_USERNAME' : 'ai_postgres', # change to your username
               'POSTGRES_PASSWORD' : 'postgres2309', # change to your password
               'POSTGRES_DBNAME' : 'test_surfers_bible_db'} # change to your db name

# create connection and cursor    
conn = ps.connect(host=credentials['POSTGRES_ADDRESS'],
                  database=credentials['POSTGRES_DBNAME'],
                  user=credentials['POSTGRES_USERNAME'],
                  password=credentials['POSTGRES_PASSWORD'],
                  port=credentials['POSTGRES_PORT'])

cur = conn.cursor()

# Create Table in AWS - RDS Postgres: 
* Initial database name = test_surfers_bible_db
* Master username = ai_postgres
* Master password = postgres2309
* DB instance identifier = test-surfers-bible-instance
* Postgres Password = postgres2309
* http://test-surfers-bible-instance.cljoljhkgpfb.ap-southeast-2.rds.amazonaws.com/

In [25]:
create_table_query = '''
      CREATE TABLE BEACH_TABLE
      (beach_id SERIAL PRIMARY KEY,
       beach_name TEXT,
       beach_latitude REAL,
       beach_longitude REAL,
       beach_state  TEXT,
       beach_municipality TEXT); '''

cur.execute(create_table_query)
conn.commit()

# INSERT TABLE:

In [26]:
%%time
for row in beach_df.itertuples():
    data_tuple = tuple(row[1:])

    print("data_tuple = ", data_tuple)
    print(" ")
    
    cur.execute("""
                        INSERT INTO BEACH_TABLE
                        (
                            beach_name,
                            beach_latitude,
                            beach_longitude,
                            beach_state,
                            beach_municipality
                         ) VALUES  (%s, %s, %s, %s, %s) ;
                """, data_tuple)    

conn.commit()

data_tuple =  ('ADDISCOT BEACH', -38.3823278, 144.2567822, 'VIC', 'SURF COAST SHIRE')

data_tuple =  ('APEX BEACH', -35.813031, 145.5470115, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BACK BEACH', -38.526863, 145.3695489, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('BANCOORA BEACH', -38.291445, 144.40711389999998, 'VIC', 'GREATER GEELONG CITY')

data_tuple =  ('BARRY BEACH', -38.517627000000005, 145.20323019999998, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('BARRYS BEACH', -38.517627000000005, 145.20323019999998, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('BAY BEACH', -38.3420493, 144.7486265, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('BELL BEACH', -38.3688055, 144.2831015, 'VIC', 'SURF COAST SHIRE')

data_tuple =  ('BELLS BEACH', -38.3688055, 144.2831015, 'VIC', 'SURF COAST SHIRE')

data_tuple =  ('BERRY BEACH', -38.517627000000005, 145.20323019999998, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('BETKA BEACH', -37.579644, 149.7480669, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('BIDDLES BEACH', -38.717677200000004, 143.72864230000002, 'VIC', 'COLAC OTWAY SHIRE')

data_tuple =  ('BIRDROCK BEACH', -38.2492901, 145.02762099999998, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('BIRRELLS BEACH', -37.922999, 147.71307, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('BLACK BEACH', -38.5357625, 145.3858399, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('BOOMANGONG BEACH', -35.834059100000005, 145.56805559999998, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BOUCHIERS BEACH', -35.8383148, 145.573699, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BOURKES BEACH NO. 1', -35.976834000000004, 145.8348082, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BOURKES BEACH NO. 2', -35.9756494, 145.8275989, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BOURKES BEACH NO. 3', -35.979502399999994, 145.8256645, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BREENS BEACH', -35.8097682, 145.5019622, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BRENTNALLS BEACH', -35.849217100000004, 145.59287340000003, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BRUCES BEACH NO. 1', -35.965768, 145.926775, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BRUCES BEACH NO. 2', -35.96546179999999, 145.914598, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BUCHANANS BEACH', -35.9563326, 145.87017659999998, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('BURGES BEACH', -37.428047, 149.713654, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('CABROOGA BEACH', -35.917294, 145.6783707, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('CARTER BEACH', -35.8217864, 145.4511248, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('CHERRY TREE BEACH', -37.9856166, 147.6522657, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('CHILDRENS BEACH', -38.522770200000004, 145.3636762, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('CHINAMAN BEACH', -38.8365578, 146.41896619999997, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('CHINAMAN LONG BEACH', -38.8365578, 146.41896619999997, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('CHINAMANS LONG BEACH', -38.8365578, 146.41896619999997, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('CLIFTON BEACH', -38.6781991, 143.1246467, 'VIC', 'CORANGAMITE SHIRE')

data_tuple =  ('COBRAWONGA BEACH NO. 1', -35.9729005, 145.7921587, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('COBRAWONGA BEACH NO. 2', -35.963856299999996, 145.7687179, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('CORNISH BEACH', -35.934859100000004, 145.7199352, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('COTTERS BEACH', -38.933474, 146.24372480000002, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('COWRIE BEACH', -38.5095419, 145.1238778, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('CRAIGIE BEACH', -38.2535951, 145.0254164, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('CRUMPETS BEACH', -38.38083889999999, 141.6413639, 'VIC', 'GLENELG SHIRE')

data_tuple =  ('DARBY BEACH', -38.969928499999995, 146.2663824, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('DAVA BEACH', -38.2454162, 145.0284023, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('DAVIS BEACH', -35.8082487, 145.53981230000002, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('DEAD RIVER BEACH', -35.8803196, 145.628053, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('DELRAY BEACH', -38.2435131, 147.36172380000002, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('DIMMICKS BEACH', -38.3824502, 144.7760781, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('DUFFYS BEACH NO. 1', -35.9726533, 145.83202649999998, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('DUFFYS BEACH NO. 2', -35.976695299999996, 145.8459006, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('EARIMIL BEACH NORTH', -38.1781377, 145.076373, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('EARIMIL BEACH SOUTH', -38.1823611, 145.0740278, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('EAST BEACH', -36.0940278, 141.96875, 'VIC', 'HINDMARSH SHIRE')

data_tuple =  ('EASTERN BEACH', -37.876152000000005, 148.015525, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('EASTERN BEACH SWIMMING POOL', -38.1469, 144.373269, 'VIC', 'GREATER GEELONG CITY')

data_tuple =  ('ELWOOD BEACH', -37.8865192, 144.98123700000002, 'VIC', 'BAYSIDE CITY')

data_tuple =  ('FARM BEACH', -38.4892843, 145.1523805, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('FINLEY BEACH', -35.82212379999999, 145.5590494, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('FISHERMANS BEACH', -38.2255685, 145.0297724, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('FIVE MILE BEACH', -38.9489665, 146.4505314, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('FLAMINGO BEACH', -38.2826805, 147.31225600000002, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('FOREST BEACH', -35.8119061, 145.5104792, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('FORGES BEACH NO. 1', -35.9963532, 145.96367180000001, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('FORGES BEACH NO. 2', -35.9928434, 145.95518069999997, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('FOSSIL BEACH', -38.241738399999996, 145.027703, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('FOSTER BEACH', -38.6961593, 146.2477959, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('FOSTERS BEACH', -38.2386287, 145.0286942, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('FOUR MILE BEACH', -36.131344899999995, 141.93256499999998, 'VIC', 'HINDMARSH SHIRE')

data_tuple =  ('FRONT BEACH', -38.334775, 144.32530769999997, 'VIC', 'SURF COAST SHIRE')

data_tuple =  ('GIBSON BEACH', -38.6694689, 143.1132926, 'VIC', 'CORANGAMITE SHIRE')

data_tuple =  ('GLENAIRE BEACH', -38.8075494, 143.46198049999998, 'VIC', 'COLAC OTWAY SHIRE')

data_tuple =  ('GLOMAR BEACH', -38.290040600000005, 147.2997639, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('GUNNAMATTA BEACH', -38.458670899999994, 144.87105659999997, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('HAWKER BEACH', -38.2568785, 145.0234648, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('HIGH SHORE', -37.509583299999996, 149.73625, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('HORSESHOE LAGOON BEACH', -35.929286299999994, 145.6971075, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('HUNTS BEACH', -35.8083006, 145.5272502, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('HUTCHINSON BEACH', -38.519651200000006, 145.2069539, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('INVERLOCH SURF BEACH', -38.646158, 145.701843, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('JACKS BEACH', -38.3370691, 145.2047933, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('JACKSON BEACH', -37.80657539999999, 148.6311232, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('JACKSONS BEACH', -37.80657539999999, 148.6311232, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('JOHANNA BEACH', -38.7702861, 143.3929156, 'VIC', 'COLAC OTWAY SHIRE')

data_tuple =  ('KILLARNEY BEACH', -38.356404299999994, 142.3101275, 'VIC', 'MOYNE SHIRE')

data_tuple =  ('KOONYA BEACH', -38.354058200000004, 144.7638364, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('KOONYA OCEAN BEACH', -38.354058200000004, 144.7638364, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('LABBETT BEACH', -35.822624600000005, 145.4642011, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('LANG LANG BEACH', -38.3074847, 145.5207836, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('LANGI OONAH BEACH', -35.9601389, 145.77819440000002, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('LAWRENCES BEACH', -35.8302017, 145.4348707, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('LAWSON BEACH', -38.692052200000006, 146.3100496, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('LITTLE RIVER BEACH', -38.3918755, 142.1855199, 'VIC', 'MOYNE SHIRE')

data_tuple =  ('LOGANS BEACH', -38.40396, 142.523784, 'VIC', 'MOYNE SHIRE')

data_tuple =  ('LOGANS BEACH WHALE NURSERY', -38.403925, 142.521592, 'VIC', 'WARRNAMBOOL CITY')

data_tuple =  ('MAIN BEACH', -37.881329, 147.996277, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('MAITLAND BEACH', -38.891043599999996, 145.9830605, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('MCGAURAN BEACH', -38.4476901, 147.1019451, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('MICKS BEACH', -38.2858333, 145.29055559999998, 'VIC', 'FRENCH ISLAND (UNINCORPORATED)')

data_tuple =  ('MILANESIA BEACH', -38.750891100000004, 143.3163484, 'VIC', 'COLAC OTWAY SHIRE')

data_tuple =  ('MILLS BEACH EAST', -38.2106811, 145.04896530000002, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('MILLS BEACH WEST', -38.2135686, 145.04433980000002, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('MOONDAH BEACH', -38.1872034, 145.0721467, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('MOONLIGHT BEACH', -38.7486552, 143.2055439, 'VIC', 'CORANGAMITE SHIRE')

data_tuple =  ('MOORES BEACH', -35.8266691, 145.5645142, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('MORGAN BEACH', -38.8658449, 145.91243290000003, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('MORGANS BEACH', -38.8658449, 145.91243290000003, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('MOTHERS BEACH', -38.2148646, 145.0347304, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('MOTS BEACH', -37.797638899999995, 148.56069440000002, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('MOUNT MARTHA BEACH NORTH', -38.2622958, 145.01722819999998, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('MOUNT MARTHA BEACH SOUTH', -38.270628, 145.0070072, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('MULBERRY BEACH', -35.818444799999995, 145.55936269999998, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('MYRONG BEACH', -36.120646799999996, 143.73212890000002, 'VIC', 'LODDON SHIRE')

data_tuple =  ('NETTLE PASS', -38.7538752, 143.3216784, 'VIC', 'COLAC OTWAY SHIRE')

data_tuple =  ('NEVINS BEACH EAST', -35.954518799999995, 145.8919986, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('NINETY MILE BEACH', -38.0860561, 147.5685753, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('NO. 16 BEACH', -38.39346629999999, 144.79153459999998, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('NORMAN BEACH', -39.0368232, 146.3220517, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('NUDE BEACH', -37.440548, 149.707002, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('NUNS BEACH', -38.3427651, 141.60815469999997, 'VIC', 'GLENELG SHIRE')

data_tuple =  ('OCEAN BEACH', -38.4817403, 145.015919, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('OLD SETTLEMENT BEACH', -38.6573169, 146.6678216, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('PADDYS BEACH', -35.926241100000006, 145.70288190000002, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('PEARSES BEACH', -38.3804818, 144.7737539, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('PEBBLY BEACH', -35.8150585, 145.5633129, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('PEPPERTREE BEACH', -35.829348100000004, 145.4189129, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('PETTMANS BEACH', -37.8294831, 148.18929709999998, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('PICNIC BEACH', -38.7149792, 146.6678011, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('POINT LEO BEACH', -38.4192237, 145.077522, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('POINT LEO SURF BEACH', -38.4249126, 145.0711015, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('PORTSEA SURF BEACH', -38.337077, 144.708825, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('PRINCETOWN BEACH', -38.7070901, 143.15908259999998, 'VIC', 'CORANGAMITE SHIRE')

data_tuple =  ('PUMPHOUSE BEACH', -35.9584196, 145.75707780000002, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('QUARRY BEACH', -37.599520399999996, 149.7308181, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('QUICKS BEACH', -35.9260224, 145.6981061, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('RANELAGH BEACH', -38.1769011, 145.07742019999998, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('RED BLUFF BEACH', -38.809332899999994, 146.2398726, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('REDBANK BEACH', -35.959937599999996, 145.854207, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('REEVES BEACH', -38.5751908, 146.95385080000003, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('RICARDO BEACH', -37.8061199, 148.620168, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('RIPPLESIDE BEACH', -38.1291412, 144.357177, 'VIC', 'GREATER GEELONG CITY')

data_tuple =  ('RIVERNOOK BEACH', -38.7169705, 143.16942969999997, 'VIC', 'CORANGAMITE SHIRE')

data_tuple =  ('ROBERTSONS BEACH', -38.6597681, 146.7299895, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('ROYAL BEACH', -38.2175346, 145.0332872, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('RYE OCEAN BEACH', -38.4186908, 144.82398600000002, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SAFETY BEACH', -38.321416, 144.9833485, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SAINT ANDREWS BEACH', -38.427085399999996, 144.834868, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SAINT HELENS BEACH', -38.1202802, 144.35997849999998, 'VIC', 'GREATER GEELONG CITY')

data_tuple =  ('SAINT PAULS BEACH', -38.353272600000004, 144.73615880000003, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SALMON BEACH', -37.8080749, 148.7255648, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('SANDRIDGE BEACH', -37.840048700000004, 144.91679169999998, 'VIC', 'PORT PHILLIP CITY')

data_tuple =  ('SANDY WATERHOLE BEACH', -38.543242299999996, 145.4440405, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('SCOTTS BEACH', -35.9264846, 145.67679099999998, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('SCOUT BEACH', -38.2147255, 145.0384625, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SECRET BEACH', -37.6088237, 149.7205724, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('SHELLEY BEACH', -38.3598611, 141.4398611, 'VIC', 'GLENELG SHIRE')

data_tuple =  ('SHELLY BEACH', -38.5518092, 143.9853365, 'VIC', 'SURF COAST SHIRE')

data_tuple =  ('SHIRE HALL BEACH', -38.2140826, 145.03991430000002, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SHOREHAM BEACH', -38.436199200000004, 145.0456439, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SMITH BEACH', -38.5039659, 145.2546314, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('SMITHS BEACH', -38.5039659, 145.2546314, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('SOMERS BEACH', -38.3951722, 145.1618103, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SORRENTO BACK BEACH', -38.3468581, 144.72826930000002, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SORRENTO FRONT BEACH', -38.3420493, 144.7486265, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SOUTH BEACH', -37.74572979999999, 142.84122280000003, 'VIC', 'ARARAT RURAL CITY')

data_tuple =  ('SOUTHCOMBE BEACH', -38.392221299999996, 142.23137659999998, 'VIC', 'MOYNE SHIRE')

data_tuple =  ('SQUEAKY BEACH', -39.0252845, 146.3053272, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('ST ANDREWS BEACH', -38.427085399999996, 144.834868, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('ST HELENS BEACH', -38.1202802, 144.35997849999998, 'VIC', 'GREATER GEELONG CITY')

data_tuple =  ('ST PAULS BEACH', -38.353272600000004, 144.73615880000003, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('STATION BEACH', -38.8295348, 143.4852416, 'VIC', 'COLAC OTWAY SHIRE')

data_tuple =  ('STEELES BEACH', -37.455496000000004, 149.69543000000002, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('SUNNYSIDE BEACH', -38.2003214, 145.0625511, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('SUTHERLANDS BEACH', -38.7562647, 143.3615023, 'VIC', 'COLAC OTWAY SHIRE')

data_tuple =  ('TAYLORS BEACH', -38.3902057, 142.17193559999998, 'VIC', 'MOYNE SHIRE')

data_tuple =  ('TEACHERS BEACH', -35.802443200000006, 145.5349981, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('THE MAHOGANYS', -37.7754167, 148.98041669999998, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('THE WRECK BEACH', -38.25352410000001, 147.34933590000003, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('THIRTEENTH BEACH', -38.28453, 144.4589399, 'VIC', 'GREATER GEELONG CITY')

data_tuple =  ('THOMSONS BEACH', -35.9127842, 145.6673161, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('THORNY BEACH', -38.5132427, 145.1822124, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('THREE MILE BEACH', -38.8647111, 146.4677023, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('TIP BEACH', -37.573890999999996, 149.758556, 'VIC', 'EAST GIPPSLAND SHIRE')

data_tuple =  ('TOORA BEACH', -38.6912791, 146.3357628, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('TRUES BEACH', -35.9584326, 145.9083035, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('TURRAS BEACH', -38.1621658, 146.3139919, 'VIC', 'LATROBE CITY')

data_tuple =  ('ULUPNA BEACH', -35.8152775, 145.5239195, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('WEISS BEACH', -35.8614234, 145.59705319999998, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('WESTERN BEACH', -38.1362992, 144.3556993, 'VIC', 'GREATER GEELONG CITY')

data_tuple =  ('WESTERN PARK BEACH', -38.3980263, 145.1836269, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('WHITES BEACH', -38.3204721, 144.340068, 'VIC', 'SURF COAST SHIRE')

data_tuple =  ('WILD DOG BEACH', -38.0299581, 141.14028169999997, 'VIC', 'GLENELG SHIRE')

data_tuple =  ('WILD DOG SHORE', -38.132811700000005, 147.33902780000003, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('WILLOW BEACH', -35.8488011, 145.5838841, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('WILSONS BEACH', -35.8687718, 145.6015384, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('WOODSIDE BEACH', -38.5521614, 146.9780383, 'VIC', 'WELLINGTON SHIRE')

data_tuple =  ('WOOLAMAI SURF BEACH', -38.538907, 145.333325, 'VIC', 'BASS COAST SHIRE')

data_tuple =  ('WOOLLEY BEACH', -38.3465923, 145.217719, 'VIC', 'MORNINGTON PENINSULA SHIRE')

data_tuple =  ('WRECK BEACH', -38.754585399999996, 143.2123915, 'VIC', 'CORANGAMITE SHIRE')

data_tuple =  ('YANAKIE BEACH', -38.8107662, 146.2694083, 'VIC', 'SOUTH GIPPSLAND SHIRE')

data_tuple =  ('ZINETTIS BEACH NO. 1', -35.9670473, 145.94064699999998, 'VIC', 'MOIRA SHIRE')

data_tuple =  ('ZINETTIS BEACH NO. 2', -35.970012200000006, 145.93563, 'VIC', 'MOIRA SHIRE')

Wall time: 6.16 s

In [27]:
cur.close()
conn.close()